# Generated by Django 4.2.4 on 2023-09-22 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='visita',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='visita',
            name='concepto_de_visita',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
