# Generated by Django 4.2.4 on 2023-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='logo_slogan_azul.png', upload_to='profile_pics'),
        ),
    ]
