# Generated by Django 4.2.4 on 2023-09-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0002_specialevent_remove_visita_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='concepto_de_visita',
        ),
        migrations.AddField(
            model_name='specialevent',
            name='prospect_profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
