# Generated by Django 4.2.4 on 2023-09-22 21:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0003_remove_visita_concepto_de_visita_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProspecto',
            fields=[
                ('ID_Perfil', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nombre_Perfil', models.CharField(max_length=255, verbose_name='Nombre del Perfil')),
                ('Rango_Edad', models.CharField(max_length=50, verbose_name='Rango de Edad')),
                ('Tipo_Vehiculo_Interes', models.CharField(choices=[('Económico', 'Económico'), ('De lujo', 'De lujo'), ('Deportivo', 'Deportivo'), ('SUV', 'SUV'), ('Camioneta', 'Camioneta'), ('Otro', 'Otro')], max_length=100, verbose_name='Tipo de Vehículo de Interés')),
                ('Intencion_Compra', models.CharField(choices=[('Inmediata', 'Inmediata'), ('3-6 meses', '3-6 meses'), ('6-12 meses', '6-12 meses'), ('Solo mirando', 'Solo mirando')], max_length=100, verbose_name='Intención de Compra')),
                ('Forma_Pago_Preferida', models.CharField(choices=[('Contado', 'Contado'), ('Crédito', 'Crédito'), ('Leasing', 'Leasing')], max_length=100, verbose_name='Forma de Pago Preferida')),
                ('Ingreso_Mensual', models.CharField(choices=[('< $10,000', '< $10,000'), ('$10,000 - $50,000', '$10,000 - $50,000'), ('> $50,000', '> $50,000')], max_length=100, verbose_name='Ingreso Mensual Aproximado')),
                ('Historial_Credito', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Sin historial', 'Sin historial')], max_length=100, verbose_name='Historial de Crédito')),
                ('Potencial_Compra', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=50, verbose_name='Potencial de Compra o Inversión')),
                ('Vehiculo_Actual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vehículo Actual (si tiene)')),
                ('Observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
            ],
        ),
    ]
