# Generated by Django 4.2.4 on 2023-09-22 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0004_perfilprospecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialevent',
            name='prospect_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mzdportal.perfilprospecto'),
            preserve_default=False,
        ),
    ]
