# Generated by Django 4.2.4 on 2023-09-23 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0005_alter_specialevent_prospect_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilprospecto',
            old_name='ID_Perfil',
            new_name='id_perfil',
        ),
    ]
