# Generated by Django 4.2.4 on 2023-09-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0006_rename_id_perfil_perfilprospecto_id_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilprospecto',
            name='Observaciones',
        ),
        migrations.AddField(
            model_name='perfilprospecto',
            name='datos_adicionales',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
