# Generated by Django 4.2.4 on 2023-09-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0008_specialevent_latitude_specialevent_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialevent',
            name='location',
        ),
    ]
