# Generated by Django 4.2.4 on 2023-09-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0009_remove_specialevent_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Registro_Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Número de Teléfono')),
                ('tipo_vehiculo', models.CharField(choices=[('mazda2_sedan', 'MAZDA2 SEDÁN 2024'), ('mazda2_hatchback', 'MAZDA2 HATCHBACK'), ('mazda3_sedan', 'MAZDA3 SEDÁN 2023'), ('mazda3_hatchback', 'MAZDA3 HATCHBACK'), ('mazda_cx3', 'MAZDA CX-3'), ('mazda_cx30', 'MAZDA CX-30'), ('mazda_cx5', 'NUEVA MAZDA CX-5'), ('mazda_cx50', 'MAZDA CX-50'), ('mazda_cx90', 'MAZDA CX-90'), ('mazda_mx5', 'MAZDA MX-5'), ('mazda_mx5_rf', 'MAZDA MX-5 RF')], max_length=50, verbose_name='Tipo de Vehículo')),
                ('rango_precio', models.CharField(max_length=50, verbose_name='Rango de Precio')),
                ('como_se_entero', models.CharField(max_length=255, verbose_name='¿Cómo se enteró del evento?')),
                ('fecha_compra_estimada', models.DateField(verbose_name='Fecha Estimada de Compra')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios o Preguntas')),
                ('recibir_noticias', models.BooleanField(default=False, verbose_name='¿Desea recibir noticias y promociones?')),
                ('metodo_contacto_preferido', models.CharField(choices=[('email', 'Correo Electrónico'), ('telefono', 'Llamada Telefónica'), ('mensaje', 'Mensaje de Texto')], max_length=50, verbose_name='Método de Contacto Preferido')),
                ('interes_financiamiento', models.BooleanField(default=False, verbose_name='¿Está interesado en opciones de financiamiento?')),
                ('vehiculo_parte_pago', models.BooleanField(default=False, verbose_name='¿Tiene un vehículo para dar en parte de pago?')),
                ('valoracion_evento', models.PositiveSmallIntegerField(choices=[(1, '1 - Malo'), (2, '2 - Regular'), (3, '3 - Bueno'), (4, '4 - Muy Bueno'), (5, '5 - Excelente')], verbose_name='Valoración del Evento')),
                ('feedback_evento', models.TextField(blank=True, verbose_name='Sugerencias o Comentarios sobre el Evento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
