# Generated by Django 4.2.4 on 2023-09-26 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0011_alter_cliente_registro_evento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_registro_evento',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mzdportal.specialevent'),
        ),
    ]
