# Generated by Django 4.2.4 on 2023-09-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0012_cliente_registro_evento_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente_registro_evento',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='cliente_registro_evento',
            name='fecha_compra_estimada',
        ),
        migrations.RemoveField(
            model_name='cliente_registro_evento',
            name='rango_precio',
        ),
    ]
