# Generated by Django 4.2.4 on 2023-09-27 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0013_remove_cliente_registro_evento_comentarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente_registro_evento',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente_registro_evento',
            name='client_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
