# Generated by Django 4.2.4 on 2023-09-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0014_remove_cliente_registro_evento_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='estado',
            new_name='concepto',
        ),
    ]
