# Generated by Django 4.2.4 on 2023-09-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0015_rename_estado_visita_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='fecha_hora_checkout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
