# Generated by Django 4.2.4 on 2023-09-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0016_alter_visita_fecha_hora_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='fecha_hora_checkout',
        ),
    ]
