# Generated by Django 4.2.4 on 2023-09-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzdportal', '0017_remove_visita_fecha_hora_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Registrado_Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('vendedor_id', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=25)),
                ('unidad_de_interes', models.CharField(max_length=100)),
            ],
        ),
    ]
